### ISSUE TITLE
尝试配置 图标图层显示标签，但是未能成功显示

### ISSUE THREAD

**Issue by bucengfangqi** [antvis/L7VP#143]
<img width="1080" alt="e80d21c37983088e537cb4e03cd537ef" src="https://github.com/antvis/L7VP/assets/22071679/4dce78bc-a678-4c63-a621-e8194d01f6d3">

项目JSON如下：
[未命名_2024-03-20 11_57_37 (1).json](https://github.com/antvis/L7VP/files/14663335/_2024-03-20.11_57_37.1.json)

**Comment by lvisei** [comment]
这条数据缺经度

![image](https://github.com/antvis/L7VP/assets/26923747/f59f5c80-22ac-4bf7-a172-ec739367a737)
