### ISSUE TITLE
🤔 [QUESTION] 无法筛选日期类型字段

### ISSUE THREAD

**Issue by guhaishuo** [antvis/L7VP#20]
### 🐛 Question description [Please make everyone to understand it]
上传的数据集中包含两个日期类型字段，但是在数据筛选过程中不显示这两个日期字段
### 🚑 Any additional [like screenshots]
![屏幕截图 2023-09-07 152104](https://github.com/antvis/L7VP/assets/33693927/fb37a82b-b706-43c3-81ee-a1f533bcc472)
![屏幕截图 2023-09-07 152203](https://github.com/antvis/L7VP/assets/33693927/82520d07-106f-449b-8d83-0fd49a81876c)

- **Version**:
- **Platform**:

**Comment by guhaishuo** [comment]
这是我测试用的数据集
[20190501_filter_upload.csv](https://github.com/antvis/L7VP/files/12545990/20190501_filter_upload.csv)

**Comment by lvisei** [comment]
@guhaishuo 
时间类型的筛选目前需要在组件栏配置，[使用文档](https://www.yuque.com/antv/l7vp/nk78fpqc7fgeymz5)

![image](https://github.com/antvis/L7VP/assets/26923747/0aab2a7a-2371-4c66-ab63-6e4c3aec47ad)

**Comment by guhaishuo** [comment]
好的，谢谢🤝因为看筛选器的源码中好像是支持日期算子的，所以有点疑惑
