### ISSUE TITLE
加载离线mapbox底图的时候，使用导出图片功能，图片上不能显示地图

### ISSUE THREAD

**Issue by evefff** [antvis/L7VP#73]
请问加载离线mapbox底图的时候，使用导出图片功能，图片上不能显示地图,只能显示添加的图层是什么原因呢

**Comment by lvisei** [comment]
我这边是 OK。复现一下步骤呢

<img width="2044" alt="image" src="https://github.com/antvis/L7VP/assets/26923747/23a65cad-7be8-4ee5-9b00-080355849ccc">

**Comment by lvisei** [comment]
如果是自己搭建的工具的话，需要在 config 里面添加 preserveDrawingBuffer，才可以导出底图 @evefff 

```js
spec: {
    map: {
      basemap: 'Gaode',
      config: {
       // for Gaode
        WebGLParams: {
          preserveDrawingBuffer: true,
        },
		// for mapbox
        preserveDrawingBuffer: true,
      },
    },
}
```

**Comment by evefff** [comment]
感谢大佬! 确实是这个问题，写的时候没有注意到gaode和mapbox,配置preserveDrawingBuffer: true,的区别
